### ISSUE TITLE
«fuaı»

### ISSUE THREAD

**Issue by ciuak** [toaq/dictionary#10]
"fuaı": {
      "official": {
        "english": "▯ is a committee.",
        "gloss": "committee"
      },
      "frame": "c"
    }

What‽ (first time seeing this root ever). Besides, what *is* a committee? Perhaps this entry should be made a bit more encyclopedic, like «chuaq».

**Comment by solpahi** [comment]
Clarified in e62876b

**Comment by ciuak** [comment]
Thanks! also, @solpahi, if you write `(fixes #123)` in the commit, it gets closed automatically.
