### ISSUE TITLE
«foı»

### ISSUE THREAD

**Issue by ciuak** [toaq/dictionary#12]
"foı": {
      "official": {
        "english": "▯ is boring/dull.",
        "gloss": "boring"
      },
      "frame": "c"
    }

As pointed out before, this word doesn't fit the pattern established in the rest of the root list:

> *root* = ▯ experiences *emotion*; ▯ is *emotion*-ed.
> *root*cā = = ▯ causes one to experience *emotion*; ▯ is *emotion*-ing.

I believe «foı» should be therefore made into ‘▯ is bored.’

**Comment by solpahi** [comment]
Agreed and updated (fa88a68).
