### ISSUE TITLE
suggestions: standard dictionary

### ISSUE THREAD

**Issue by Pantyhose-X** [toaq/dictionary#155]
This is the corpus of all scientific terms https://github.com/Pantyhose-X/Logical#word-source-data

---
Please create a group at https://rvlt.gg/ and let's discuss some questions

**Comment by leafpool243** [comment]
??????

Toaq isn’t looking to have a word for *every single concept*... And a simple program would not be adequate to generate that many words and put them into the dictionary

In addition, machine translation is not trustworthy enough yet.
