### ISSUE TITLE
«guo»

### ISSUE THREAD

**Issue by uakci** [toaq/dictionary#16]
"guo": {
      "official": {
        "english": "▯ is a repetition/instance of ▯.",
        "gloss": "instance"
      }
    }

Frame is unclear. There are two options:
- If guo<sub>1</sub> constitutes a separate ‘type’ (i.e., «guo go lủfē» isn't itself «lufē»), and if the experimental «lo» creates such a type itself, then it ought to be ‘c 0.’
- Otherwise, it's plain ol' ‘0 0.’

**Comment by Ilmen-vodhr** [comment]
Clarifying the type of the second argument (lû/proposition, as opposed to baq/kind) would also be a good thing.

**Comment by uakci** [comment]
Let's say that the consensus is ‘c 0’ and stick to that for now.
