### ISSUE TITLE
«bıa»

### ISSUE THREAD

**Issue by ciuak** [toaq/dictionary#2]
The definition for «bıa» reads:

> ▯ is sick/ill; ▯ is sick/ill with ▯.

And the proposed frame is ‘c c’.

That bıa<sub>2</sub> is concrete implies that it is some kind of description of a disease, but the best way to describe a disease is with respect to the one(s) who has (have) it – a property of bıa<sub>1</sub>. (Nothing restricts us from referring to properties with «mı».)

Therefore, I propose that «bıa» be a LEO (‘c 1’). This way we can say:

> «bỉa hó lî ke pỏ hó ga pỉu pa kỉarēo»
> He is ill with reddened skin. / He is suffering from (a disease which involves) the skin being red.

And we can still say:

> «bỉa jí mí hỏaq hủohūa»  
> I have an ear inflammation.

…if only «mí hỏaq hủohūa» is defined as something like «lî ke pỏ hó ga pỉu pa nỏıgē ru bẻqdūı».

Please definitely let me know if something I said didn't make sense to you.

**Comment by solpahi** [comment]
I agree with (c 1).

**Comment by ciuak** [comment]
I'll make it ‘c 1’ for now.
