### ISSUE TITLE
«jua»

### ISSUE THREAD

**Issue by ciuak** [toaq/dictionary#23]
"jua": {
      "official": {
        "english": "▯ is weird/strange/bizarre.",
        "gloss": "weird"
      },
      "frame": "c"
    }

The Lojban community prides itself in ostentative saying of the phrase ‘jai cizra’; shall we, too?

**Comment by solpahi** [comment]
I'm not entirely sure what you are asking. I don't think the jai is necessary; **jua** can refer both to things and to situations or facts.

**Comment by ciuak** [comment]
If so, the answer is no. Thanks for clarifying.

**Comment by ciuak** [comment]
(but shall we have ‘0’ as the frame anyway?)
