### ISSUE TITLE
«jıoq»

### ISSUE THREAD

**Issue by ciuak** [toaq/dictionary#25]
"jıoq": {
      "official": {
        "english": "▯ calculates ▯.",
        "gloss": "calculate"
      },
      "frame": "c c"
    }

It's unclear to me how this word should be used and what makes it different from «mieq».

**Comment by Ilmen-vodhr** [comment]
To me:
mıeq = ▯ observes the outside world in order to find what satisfies property ▯.
jıoq = ▯ computes (by executing some algoritm) what satisfies property ▯ (without necessarily needing information from the outside world).

**Comment by ciuak** [comment]
@Ilmen-vodhr:

> To me:
> mıeq = ▯ observes the outside world in order to find what satisfies property ▯.
> jıoq = ▯ computes (by executing some algorithm) what satisfies property ▯ (without necessarily needing information from 
> the outside world).

Sure enough, but that would mean «mıeq» and «jıoq» have the same frame. Perhaps let's leave it to @acotis to explain why he keyed in ‘c c’ for «mieq».

**Comment by acotis** [comment]
Probably a typo, unless its definition used to have a different wording.  In any case it's safe to move it to the (c 1) frame.

**Comment by ciuak** [comment]
@acotis, I agree that ‘c 1’ is more sensible, but in order to effect that, we'll need @solpahi to change the official definition so as to reflect the frame. For now, it ought to stay as ‘c c,’ because there's no mention or even suggestion of ‘1’ in the English definition.

**Comment by acotis** [comment]
The definition I see on Toadua is `predicate: ‘measure’; ◌ measures/evaluates/determines what satisfies property ◌.`  That seems to pretty much nail down the frame as (c 1).

**Comment by ciuak** [comment]
@acotis, yes, «mıeq» is a solid ‘c 1’ – the word ‘property’ gives it all away, doesn't it. It's «jıoq» that we're talking about here.

**Comment by acotis** [comment]
Oh, heh. All right, so then I guess the question was why I designated «jioq» as (c c).  For that I have no answer, I was never sure about that choice I think.

**Comment by ciuak** [comment]
It's okay to doubt, which is why I made this issue.

**Comment by solpahi** [comment]
Well okay, let's make it (c 1).
