### ISSUE TITLE
«joaı»

### ISSUE THREAD

**Issue by ciuak** [toaq/dictionary#26]
"joaı": {
      "official": {
        "english": "▯ looks/searches for something which satisfies property ▯ among ▯.",
        "gloss": "seek"
      },
      "frame": "c 1 c"
    }

In ‘frames-list.txt,’ @acotis (in?-)famously wrote that the ‘c 1 c’ frame is broken and should be replaced with ‘c c 1.’ After some, «huaq»<sup>3</sup> was remade into ‘c c 1,’ having been ‘c 1 c’ before. What about «joaı», then?

**Comment by ciuak** [comment]
This issue also applies to «nua», «doa», «suı», and «soq».

**Comment by solpahi** [comment]
I would be interested in the opinions of more people here. 

"I'm looking for water" becomes more complicated without using serial magic, because you have to skip a place. I think this is true most of the time when using **joaı**. It is true that serials become simpler if the places are swapped, but I really dislike having to use FI words...

So there is a trade-off. What do the people think?

**Comment by ciuak** [comment]
You mentioned the case of ‘I'm looking for water,’ but I also mentioned the other 4 words which, I think, gain on intuitiveness when the abstraction slot is moved to the back. And «joaı» doesn't need an x<sub>3</sub> place anyway; that would imply that there *is* a set (not in the sense of the word ‘set’ that annoys you) of things that the x<sub>1</sub> searches among. Allow me to demonstrate:

> joaı: ▯ searches for property ▯; ▯ looks for something which satisfies property ▯.
> «jỏaı jí lî pỏjī jảkē» ‘I'm looking for my jacket.’ (doesn't imply any mode of searching; specifically, doesn't imply that there's a set of things I'm search among, and I don't even need to imply ‘everything’ as this set.)
> «jẻıjōaı jí pójī jảkē»; «jỏaı pỏjī jảkē jí» – as above
> «meajōaı» could be used for the old joaı, although from after the swapping: ‘▯ searches through ▯ for something which satisfies ▯.’ (Think ‘durchsuchen.’)

Thoughts?

**Comment by solpahi** [comment]
> And «joaı» doesn't need an x3 place anyway; that would imply that there is a set (not in the sense of the word ‘set’ that annoys you) of things that the x1 searches among

The third place is only there when you fill it. If you don't, then no such thing is implied.

As for **nua** and **doa**, I would consider them separately, but I could see swapping their second and third places.

(Fun fact: "give" in Mandarin and "give" in Cantonese differ in the order of the second and third places (gift and recipient). Of course, neither require a property.)

**Comment by ciuak** [comment]
Okay. I agree that letting the least commonly used place sit at the end seems just about fitting. I'll create a new discussion for the remaining 4 words.
