### ISSUE TITLE
«jeaq»

### ISSUE THREAD

**Issue by ciuak** [toaq/dictionary#27]
"jeaq": {
      "official": {
        "english": "▯ increases; ▯ increases in how much it satisfies property ▯.",
        "gloss": "increase"
      },
      "frame": "0; c 1"
    }

Definition unclear; sounds like a plausible candidate for a ‘1; c 1.’

**Comment by solpahi** [comment]
I have updated the wording. The frame is given correctly as [(0) (c 1)].
