### ISSUE TITLE
«luao»

### ISSUE THREAD

**Issue by uakci** [toaq/dictionary#31]
"luao": {
      "official": {
        "english": "▯ is a lip (general sense).",
        "gloss": "lip"
      },
      "frame": "c"
    }

Pardon my ignorance, but how can ‘lip’ have a general sense? ‘Orifice’?

**Comment by solpahi** [comment]
I meant it as in "a projecting rim of an open container or of a part of the body"

**Comment by ciuak** [comment]
Then let us change the definition to ‘▯ is a lip (general sense); ▯ is a projecting rim of an opening.’

(Let's also not concern ourselves with keeping the dictionary at <toaq.org/dictionary/> up to date with what's happening here, shall we? Modifying two databases at once is getting very cumbersome.)
