### ISSUE TITLE
«lıaq»

### ISSUE THREAD

**Issue by ciuak** [toaq/dictionary#32]
"lıaq": {
      "official": {
        "english": "▯ is a ▯-tuple.",
        "gloss": "tuple"
      }
    }

lıaq<sub>2</sub>: «peı» numeral (‘c c,’ or Ilmen's ‘c n’) or like ko<sub>3</sub> (‘c 1’)?

**Comment by ciuak** [comment]
Also applies to «chıo».

**Comment by solpahi** [comment]
Canonically, there is no such thing as a numeric place.

**lıaq** should be (c 1).
