### ISSUE TITLE
«moı» & «sıo»

### ISSUE THREAD

**Issue by ciuak** [toaq/dictionary#35]
"moı": {
      "official": {
        "english": "▯ thinks / is having a thought; ▯ thinks thought ▯.",
        "gloss": "think"
      },
      "frame": "c 0"
    },
    "sıo": {
      "official": {
        "english": "▯ is a thought/idea.",
        "gloss": "thought"
      },
      "frame": "c"
    }

moı<sub>2</sub> is a ‘0’… and yet sıo<sub>1</sub> is ‘c’?

**Comment by ciuak** [comment]
@solpahi, more precisely: should «sio» be restricted to propositions? (not talking about the frame, of course)

**Comment by solpahi** [comment]
To me, thoughts and ideas are propositions. I don't think the definitions need changing. Example usages would show how to use the places, if someone doesn't know to how to interpret "thought", or there can be mention of it in the notes.

>moı2 is a ‘0’… and yet sıo1 is ‘c’?

As you are aware by now, the signatures are just combination rules for serials.  

I think this can be closed.

**Comment by ciuak** [comment]
You're right, of course. I had made the issue before I was made to realise that signatures aren't fully semantic(al).
