### ISSUE TITLE
«teoq»

### ISSUE THREAD

**Issue by ciuak** [toaq/dictionary#42]
"teoq": {
      "official": {
        "english": "▯ is a question.",
        "gloss": "question"
      },
      "frame": "c"
    }

Could as well be a ‘0’ – the English doesn't show.

**Comment by solpahi** [comment]
If a question is a quote, then it can't be 0.

**Comment by ciuak** [comment]
Is a question a quote?

**Comment by solpahi** [comment]
Let's see:

(1) **Tẻoq mó bủa súq hı ráı moq teo da.**
(2) **Tẻoq lû bủa súq hı ráı da.**

I would definitely accept sentence (1) (''where do you live?" is a question"). If (1) is correct, then (2) shouldn't be. Since I deem (1) correct, I deem (2) incorrect. Ergo, the signature should be (c).

**Comment by ciuak** [comment]
@solpahi, please see if the change fits you

**Comment by solpahi** [comment]
Eh, I guess. Brackets are not really used like that in any other definition (defining a type), but the alternative would be `The quote ___ is a question.` which isn't that great either. The only other option would be to put that information in the notes.
