### ISSUE TITLE
«puaqsī»

### ISSUE THREAD

**Issue by uakci** [toaq/dictionary#53]
> ▯ focuses on touch feeling ▯.

This definition feels off. There are two possibilities:
1. ‘Feeling’ probably refers to moı₂, so the word is redundant to «puaqgāı».
2. ‘Touch feeling’ is a gerund of ‘touch feel,’ a phrase I've never seen before whose existence dictionaries seem to deny. (I did check.) The definition should be rephrased, possibly into something like this: ‘▯ focuses on feeling ▯ by touch.’ The same then applies to «puaqgāı».

Please explain, @solpahi.

**Comment by lynn** [comment]
It is only as redundant to puaqgāı as “listen” is redundant to “hear”.

puaqsī = puaqgāı + paying attention (“focusing”).

It's just that English has no good pair of verbs for the sense of touch (feel → ?), the way it does for vision (see → watch) and auditory sense (hear → listen).

**Comment by uakci** [comment]
Half-a-year-later uakci here: I have changed my mind since. (Also, thanks, @lynn, for the commentary.) I'll close the issue if nobody has anything against it.
