### ISSUE TITLE
«meakūq»

### ISSUE THREAD

**Issue by uakci** [toaq/dictionary#57]
> ▯ mentions ▯ to ▯.

Corellation between «mea» and «kuq» and the definition is unclear.
Note that @acotis keyed it in as ‘c 0 c,’ but it looks like ‘c c c,’ which is like «kuq».

**Comment by solpahi** [comment]
It inherits **kuq**'s signature of (c c c), the second place is text.

The correlation is that **mẻa B ke tỏa kǔq A hóa C**; B is among the words that A says to C, i.e., A mentions B to C.
