### ISSUE TITLE
«burūaq»

### ISSUE THREAD

**Issue by Ilmen-vodhr** [toaq/dictionary#63]
```
{
    "toaq": "burūaq",
    "type": "predicate",
    "english": "▯ lies / asserts untruth ▯.",
    "gloss": "lie",
    "keywords": [],
    "frame": "c 0",
    "distribution": "d d",
    "notes": [],
    "examples": [],
    "fields": []
}
```

@ [https://uakci.pl/toadua/##2RHBnD6mds]():
> [uakci]  -1, see \@Ilmen's #ypIf3LarK
> [Ilmen]  −1, agreed. It's not that bad, but I'd prefer something based on "dishonest" or "deceive". "ruaqhūı" (#x9Dk6J0ca) is also a good alternative candidate.
> [Ilmen]  "burūaq" comes from "rủaq go sa bú", and that's probably an acceptable metaphor, but technically one can lie by asserting something true, provided one does not actually believe it to be true and dishonestly assert it (whether or not it is actually true doesn't matter, what is significant is the dishonest behavior).
> [uakci]  my reason for downvoting the entry was that «burūaq» would most likely be analysed as «ruaq bủ»/2, which is more like \@Ilmen's definition: ‘to say that (something) is false.’``

**Comment by solpahi** [comment]
Changed in 98570e4
