### ISSUE TITLE
«die»

### ISSUE THREAD

**Issue by acotis** [toaq/dictionary#90]
It currently isn't clear whether this word means `___ suggests that ___ is so` or `___ suggests that ___ should be so`.

**Comment by xorxes** [comment]
die jí gúko ka. 

I think suggest/propose is more useful.

For suggest/indicate perhaps something based on tua X mîu há Y. miutua?

**Comment by acotis** [comment]
One reason to prefer the first option is that you can use it to generate the second option (`dỉe ȷí ȷûoq ___`) but not vice versa, as far as I can tell.

I think that expansion of suggest/indicate is off, since suggesting something doesn't always make someone opine it. I almost wonder if **ruaq dảı** or something might be appropriate.

**Comment by acotis** [comment]
Or maybe **tua mỏı** or **tua sỉ**. This would make it more analogous to "mention" and would allow things like `dỉe ȷí baq ȷủo ka`, "I suggest a letter".

**Comment by xorxes** [comment]
"I suggest a letter (be sent)" is in the "propose" sense, right?

For the "indicate" sense there's the non-volitional and volitional senses as well:

"The evidence suggested they were murdered" vs "the detective suggested they were murdered".

Maybe not **tua miu** but **tua taole miu**

For performative use obviously only volitional makes sense.

**Comment by acotis** [comment]
While looking for something else, I've just found Hoemai's thoughts on the matter:

![image](https://user-images.githubusercontent.com/6502776/85213020-efb58000-b326-11ea-902b-2d001bf09484.png)

The link leads to this page: https://en.m.wiktionary.org/wiki/suggest

And the third definition reads:

```
(transitive) To mention something as an idea, typically in order to recommend it quotations:

    I’d like to suggest that we go out to lunch. I’d like to suggest going out to lunch.

    The guidebook suggests that we visit the local cathedral, which is apparently beautiful.
```
