### ISSUE TITLE
Days, months, and seasons — individuals vs equivalence classes

### ISSUE THREAD

**Issue by acotis** [toaq/dictionary#95]
Consider these predicates:

- **mıochāq**: `predicate: ‘saturday’; ◌ is a Saturday.`
- **shıȷūe**: `◌ is a January` (coined by me, non-official)
- **loqcāo**: `◌ is summer`

Notice how the last of these is an odd one out. It refers to SUMMER, the abstract entity that shows its face for three months out of every year (in many parts of the world) rather than simply referring to a summer. I think all time words should be defined to refer to individual instances and that the abstract entities should be formed with compounds, like **loqcāozȳ**.

Or, possibly **baq**. I can't say for sure as I don't understand that word too well yet.

**Comment by solpahi** [comment]
![grafik](https://user-images.githubusercontent.com/7430686/85589372-cd33a780-b643-11ea-92ae-0a99793a519f.png)

So your definition of **shıjūe** is the same as the canonical one.

The same goes for **loqcāo**. See for instance **Jảq lôi jí baq kỏacāo da** "I really hate winter" ([Twe Lesson 11](https://toaq.github.io/TwE/11/)).

**Comment by acotis** [comment]
Perfect! In that case the only issue here is that the currently entered definitions are slightly misleading, so I'll tag this issue and assign it to you, the caqche of the canon.
