### ISSUE TITLE
«sarālīa» is out of sync with other country vocab

### ISSUE THREAD

**Issue by acotis** [toaq/dictionary#96]
Most country vocab is formulated as a base predicate X meaning `___ pertains to the culture of country X`, then at least two compound predicates Xgūa meaning `___ is the country X` and Xtōaq meaning `___ is a language spoken in country X`. However, **sarālīa** is currently defined as `___ is Australia`, which breaks the pattern.

**Comment by lynn** [comment]
Australia the country is **Oseılıagua**, and **Saralıa** refers to the continent, in line with **Afarı, Eoropa, Asıa** etc.
