### ISSUE TITLE
Is «rıofā» agentive?

### ISSUE THREAD

**Issue by acotis** [toaq/dictionary#99]
If it parallels **fa**, then it is. And in that case, **rıodūo** should probably parallel **duo**, and refer to non-agentive air travel. But **rıodūo** currently gets used for "wind" (unofficially), so that would have to change.

**Comment by lynn** [comment]
Modern Toaq Wisdom: yes, it is. "Float through the air non-agentively" is **rıoduy**. Wind is **ırue**.
